apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-app
  namespace: default
  labels:
    app: prometheus-metrics-app
spec:
  type: ClusterIP
  selector:
    app: prometheus-metrics-app
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None